using UnityEditor;
using UnityEngine;
using System.IO;

namespace Unity.BestPractices.Editor
{
    /// <summary>
    /// Creates a Unity-optimised <c>.gitignore</c> file at the project root.
    /// Accessible via the menu: <b>Window → Best Practices → Generate .gitignore</b>.
    /// </summary>
    /// <remarks>
    /// The generated file excludes common Unity-generated directories (Library, Temp, Logs),
    /// IDE project files (Visual Studio, Rider), OS metadata files, and build artifacts.
    /// </remarks>
    public static class GenerateGitIgnore
    {
        /// <summary>
        /// Creates or overwrites the <c>.gitignore</c> file at the Unity project root.
        /// Prompts the user for confirmation if the file already exists.
        /// </summary>
        [MenuItem("Window/Best Practices/Generate .gitignore")]
        public static void Execute()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string gitignorePath = Path.Combine(projectRoot, ".gitignore");

            if (File.Exists(gitignorePath))
            {
                bool overwrite = EditorUtility.DisplayDialog(
                    "Generate .gitignore",
                    ".gitignore already exists. Overwrite it?",
                    "Overwrite",
                    "Cancel"
                );
                if (!overwrite) return;
            }

            string content = @"# Unity generated
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/
[Mm]emoryCaptures/
[Rr]ecordings/

# Asset meta data should only be ignored when the corresponding asset is also ignored
!/[Aa]ssets/**/*.meta

# Autogenerated Packages
/[Pp]ackages/packages-lock.json

# Visual Studio / Rider
.vs/
.idea/
*.csproj
*.sln
*.suo
*.user
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# OS generated
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Builds
*.apk
*.aab
*.unitypackage
*.app

# Crashlytics
crashlytics-build.properties

# Gradle
/[Aa]ssets/Plugins/Android/baseProjectTemplate.gradle
/[Aa]ssets/Plugins/Android/launcherTemplate.gradle
/[Aa]ssets/Plugins/Android/mainTemplate.gradle
/[Aa]ssets/Plugins/Android/gradleTemplate.properties
";

            File.WriteAllText(gitignorePath, content);
            Debug.Log($"[BestPractice] .gitignore created at: {gitignorePath}");
        }
    }
}

